version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: install python imports
          command: pip install requests
      - run:
          name: validate forms against codebook
          command: cd validation && python2.7 validate.py
